# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('blog', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=None, max_length=33, unique=True, verbose_name='用户名'),
        ),
    ]
