# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190719_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
