# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190719_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='name',
        ),
    ]
