# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='文章标题')),
                ('category', models.IntegerField(choices=[(1, '未分类'), (2, '技术'), (3, '杂谈'), (4, '感悟')], default=1, verbose_name='文章分类')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='博客名称')),
                ('user', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='所属博客'),
        ),
    ]
